project_id = "kkwebaqtenbqlyeyqnzs"

[functions.weather-insights]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.weather-proxy]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false